export default function Head() {
  return (
    <>
      <title>小花匠</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

      {/* for rss */}
      <link rel="alternate" type="application/rss+xml" href="/rss/feed.xml" title="RSS Feed" />
      <link rel="alternate" type="application/rss+json" href="/rss/feed.json" title="RSS Feed" />
      <link rel="alternate" type="application/atom+xml" href="/rss/atom.xml" title="RSS Feed" />
    </>
  )
}
